---
- name: Installing plugins
  shell: "vagrant plugin install {{ item }}"
  loop: "{{ vagrant_plugins | default([]) }}"

- name: Running Vagrant setup
  include_tasks: run-single-setup.yml
  loop: "{{ vagrant_src }}"
  loop_control:
    loop_var: vagrant
  args:
    apply:
      become_user: "{{ vagrant.user | default(ansible_user) }}"
